name: Deploy

on:
  push:
    branches: [ main ]  # Adjust to your main branch name
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: self-hosted # Use your self-hosted runner
    
    steps:
      - name: Navigate to correct directory
        run: |
          cd /home/Reinsdyr-Broker-ProveProveEksamen/server
          echo "Current directory: $(pwd)"
      
      - name: Git pull latest changes
        working-directory: /home/Reinsdyr-Broker-ProveProveEksamen/server
        run: |
          git fetch --all
          git reset --hard origin/main  # Adjust to your main branch name
      
      - name: Check for package changes
        working-directory: /home/Reinsdyr-Broker-ProveProveEksamen/server
        id: check-changes
        run: |
          if git diff --name-only HEAD@{1} HEAD | grep "package.json"; then
            echo "npm_install=true" >> $GITHUB_OUTPUT
          else
            echo "npm_install=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies if needed
        if: steps.check-changes.outputs.npm_install == 'true'
        working-directory: /home/Reinsdyr-Broker-ProveProveEksamen/server
        run: npm ci  # Using npm ci for more predictable installs
      
      - name: Reload PM2
        working-directory: /home/Reinsdyr-Broker-ProveProveEksamen/server
        run: |
          pm2 reload server  # Replace with your actual PM2 app name
