name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Git pull latest changes
        run: |
          git pull
      
      - name: Install dependencies if needed
        run: npm ci
      
      - name: Reload PM2
        run: |
          pm2 restart all
